# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
def ramdom_matrix():
    ok=False
    while not ok:
        try:
            n=int(input('Введіть кількість стопців і рядків в квадратній матриці: '))
            break
        except :
            print('Неправильно введені дані')
    while n<=0 :
        print('Неправильно введені дані') 
        while not ok:
            try:
                n=int(input('Введіть кількість стопців і рядків в квадратній матриці: '))
                break
            except :
                print('Неправильно введені дані')
    import numpy as np
    matrix = np.random.randint(10, size = (n, n))
    print(matrix)
    if n==1:
        det_a=matrix[0,0]
        print('Визначник матриці дорівнює ', det_a)
    elif n==2:
        det_a=matrix[0,0]*matrix[1,1]-matrix[1,0]*matrix[0,1]
        print('Визначник матриці дорівнює ', det_a)
    elif n==3:
        det_a=matrix[0,0]*matrix[1,1]*matrix[2,2]+matrix[2,0]*matrix[0,1]*matrix[1,2]+matrix[0,2]*matrix[1,0]*matrix[2,1]-matrix[0,2]*matrix[1,1]*matrix[2,0]-matrix[0,1]*matrix[1,0]*matrix[2,2]-matrix[0,0]*matrix[1,2]*matrix[2,1]
        print('Визначник матриці дорівнює ', det_a)
    else:
        import numpy
        det_a = numpy.linalg.det(matrix)
        print('Визначник матриці дорівнює ', round(det_a ,2))
ramdom_matrix()

[[3 0 0]
 [2 0 8]
 [8 9 0]]
Визначник матриці дорівнює  -216
